In [39]:
from astropy.io import fits
import numpy as np
from astropy.table import Table
import pandas as pd
import glob
from astropy.table import vstack
import seaborn as sns

In [40]:
df = pd.read_csv("IGAPs-emitters_simbad1arcs.csv")

In [41]:
df

,Name,RAJ2000,DEJ2000,GLON,GLAT,SourceID,ePos,Class,pStar,pGalaxy,...,R_x,J,H,K,u,g,r_xa,i,z,angDist
0,J194407.42+302330.8,296.030917,30.391885,65.664704,3.196313,470950-3-22952,0.033,-1.0,1.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,18.220,16.411,NaN,0.168245
1,J193916.47+295625.4,294.818643,29.940402,64.753867,3.886151,455814-3-14394,0.048,99.0,1.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,17.601,16.871,NaN,0.011652
2,J193259.22+293449.0,293.246746,29.580274,63.776702,4.907186,419725-1-14923,0.040,99.0,0.95,0.05,...,NaN,NaN,NaN,NaN,NaN,NaN,18.933,17.972,NaN,0.030445
3,J193350.35+300314.5,293.459805,30.054030,64.283071,4.971270,419728-3-9582,0.037,-1.0,1.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.113228
4,J193538.67+301627.5,293.911114,30.274298,64.664957,4.734672,420450-3-16078,0.046,99.0,0.05,0.94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.568631
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4810,J200106.16+305600.4,300.275670,30.933448,68.001429,0.338110,474815-4-4988,0.064,-1.0,1.00,0.00,...,NaN,NaN,NaN,NaN,NaN,17.414,15.687,NaN,NaN,0.032701
4811,J200103.08+312305.2,300.262834,31.384778,68.378932,0.585739,572325-1-9694,0.049,-1.0,1.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,17.930,16.913,NaN,0.035513
4812,J193851.00+282741.4,294.712493,28.461510,63.415617,3.244483,571565-2-6295,0.026,-1.0,1.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,18.369,16.896,NaN,0.197284
4813,J194657.47+291706.8,296.739465,29.285215,65.012424,2.111001,626263-3-22491,0.026,-1.0,1.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,16.054,15.387,NaN,0.046455
4814,J194725.96+293304.7,296.858158,29.551299,65.294604,2.155432,398934-4-24535,0.038,-1.0,1.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,15.734,15.253,NaN,0.027536

In [42]:
df["main_type"]

0                   EmLine*
1                   EmLine*
2                   EmLine*
3       CataclyV*_Candidate
4                    EclBin
               ...
4810           LongPeriodV*
4811                EmLine*
4812                EmLine*
4813                EmLine*
4814                EmLine*
Name: main_type, Length: 4815, dtype: object

In [43]:
np.unique(df["main_type"])

array(['**', 'AGB*_Candidate', 'Ae*', 'Ae*_Candidate', 'BYDraV*', 'Be*',
       'Be*_Candidate', 'BlueStraggler', 'CataclyV*',
       'CataclyV*_Candidate', 'ChemPec*', 'ClassicalCep', 'EclBin',
       'EmLine*', 'Galaxy', 'HIIReg', 'HighMassXBin', 'HighPM*',
       'HotSubdwarf_Candidate', 'Infrared', 'LongPeriodV*',
       'LongPeriodV*_Candidate', 'Low-Mass*', 'MidIR', 'Mira', 'Nova',
       'OrionV*', 'PlanetaryNeb', 'PlanetaryNeb_Candidate', 'PulsV*',
       'RRLyrae', 'RRLyrae_Candidate', 'RSCVnV*', 'RotV*', 'SB*', 'Star',
       'Symbiotic*', 'TTauri*', 'TTauri*_Candidate', 'Transient', 'UV',
       'Variable*', 'WhiteDwarf', 'WhiteDwarf_Candidate', 'WolfRayet*',
       'WolfRayet*_Candidate', 'X', 'XrayBin', 'YSO', 'YSO_Candidate',
       'delSctV*', 'smmRad'], dtype=object)

In [44]:
dict_simbad = {}
for i in np.unique(df["main_type"]):
    m = df["main_type"] == i
    type_simbad = df[m]
    dict_simbad[i] = len(type_simbad)

In [45]:
dict_simbad

{'**': 3,
 'AGB*_Candidate': 10,
 'Ae*': 6,
 'Ae*_Candidate': 1,
 'BYDraV*': 97,
 'Be*': 185,
 'Be*_Candidate': 7,
 'BlueStraggler': 1,
 'CataclyV*': 64,
 'CataclyV*_Candidate': 33,
 'ChemPec*': 1,
 'ClassicalCep': 1,
 'EclBin': 166,
 'EmLine*': 1646,
 'Galaxy': 6,
 'HIIReg': 1,
 'HighMassXBin': 2,
 'HighPM*': 15,
 'HotSubdwarf_Candidate': 1,
 'Infrared': 2,
 'LongPeriodV*': 162,
 'LongPeriodV*_Candidate': 87,
 'Low-Mass*': 1,
 'MidIR': 4,
 'Mira': 10,
 'Nova': 6,
 'OrionV*': 142,
 'PlanetaryNeb': 37,
 'PlanetaryNeb_Candidate': 37,
 'PulsV*': 2,
 'RRLyrae': 6,
 'RRLyrae_Candidate': 3,
 'RSCVnV*': 175,
 'RotV*': 1,
 'SB*': 1,
 'Star': 289,
 'Symbiotic*': 5,
 'TTauri*': 218,
 'TTauri*_Candidate': 3,
 'Transient': 1,
 'UV': 1,
 'Variable*': 17,
 'WhiteDwarf': 30,
 'WhiteDwarf_Candidate': 11,
 'WolfRayet*': 2,
 'WolfRayet*_Candidate': 1,
 'X': 2,
 'XrayBin': 1,
 'YSO': 651,
 'YSO_Candidate': 657,
 'delSctV*': 3,
 'smmRad': 1}

In [46]:
# Count the number of objects of each type and store it in a dictionary
dict_simbad_ = df["main_type"].value_counts().to_dict()

In [47]:
dict_simbad_

{'EmLine*': 1646,
 'YSO_Candidate': 657,
 'YSO': 651,
 'Star': 289,
 'TTauri*': 218,
 'Be*': 185,
 'RSCVnV*': 175,
 'EclBin': 166,
 'LongPeriodV*': 162,
 'OrionV*': 142,
 'BYDraV*': 97,
 'LongPeriodV*_Candidate': 87,
 'CataclyV*': 64,
 'PlanetaryNeb_Candidate': 37,
 'PlanetaryNeb': 37,
 'CataclyV*_Candidate': 33,
 'WhiteDwarf': 30,
 'Variable*': 17,
 'HighPM*': 15,
 'WhiteDwarf_Candidate': 11,
 'AGB*_Candidate': 10,
 'Mira': 10,
 'Be*_Candidate': 7,
 'Ae*': 6,
 'RRLyrae': 6,
 'Nova': 6,
 'Galaxy': 6,
 'Symbiotic*': 5,
 'MidIR': 4,
 '**': 3,
 'RRLyrae_Candidate': 3,
 'delSctV*': 3,
 'TTauri*_Candidate': 3,
 'Infrared': 2,
 'X': 2,
 'HighMassXBin': 2,
 'WolfRayet*': 2,
 'PulsV*': 2,
 'BlueStraggler': 1,
 'HIIReg': 1,
 'HotSubdwarf_Candidate': 1,
 'SB*': 1,
 'UV': 1,
 'XrayBin': 1,
 'ClassicalCep': 1,
 'Low-Mass*': 1,
 'Transient': 1,
 'RotV*': 1,
 'smmRad': 1,
 'ChemPec*': 1,
 'Ae*_Candidate': 1,
 'WolfRayet*_Candidate': 1}